# 0.0 Imports

In [44]:
import pandas as pd
import numpy as np
import inflection
import locale
import plotly.express as px
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

In [ ]:
# Inicializa o geolocalizador
geolocator = Nominatim(user_agent="my_app", timeout=10)

geocode = RateLimiter(
    geolocator.geocode,
    min_delay_seconds=1,   # respeita limite da API
    swallow_exceptions=True
)

# Função para pegar latitude e longitude de uma cidade
def get_lat_lon(city_name):
    if city_name in cache:
        return cache[city_name]
    
    location = geocode(city_name)
    
    if location:
        coords = (location.latitude, location.longitude)
    else:
        coords = (None, None)
    
    cache[city_name] = coords
    return coords
    

def define_safra(row):
    if row['mes'] < 5:
        ano_inicio = row['ano'] - 1
        ano_fim = row['ano']
    else:
        ano_inicio = row['ano']
        ano_fim = row['ano'] + 1
    return f"{str(ano_inicio)[-2:]}/{str(ano_fim)[-2:]}"

In [46]:
data = pd.read_excel('../data/planilha_vendas.xlsx')

c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\openpyxl\worksheet\_read_only.py:81: UserWarning: Data Validation extension is not supported and will be removed
  for idx, row in parser.parse():

# 1.0 Descrição dos Dados

In [47]:
df1 = data.copy()

## 1.1. Tamanho dos Dados

In [48]:
print(f'Numero de linhas é de: {df1.shape[0]}')
print(f'Numero de linhas é de: {df1.shape[1]}')

Numero de linhas é de: 304
Numero de linhas é de: 16

## 1.2. Coluna dos Dados

In [49]:
old_cols = ['Emissor', 'No Pedido', 'Revenda', 'Cidade', 'Produto', 'Quantidade',
       'Preço', 'Total', 'Data de emissão', 'Data de Faturamento',
       'Tipo de Vencimento', 'Data de Vencimento', '% Comissão',
       'Comissão Total', 'Comissão 1', 'Comissão 2']

snakecase = lambda x: inflection.underscore( x )

new_cols = list( map( snakecase, old_cols ) )

df1.columns = new_cols
df1.columns

Index(['emissor', 'no pedido', 'revenda', 'cidade', 'produto', 'quantidade',
       'preço', 'total', 'data de emissão', 'data de faturamento',
       'tipo de vencimento', 'data de vencimento', '% comissão',
       'comissão total', 'comissão 1', 'comissão 2'],
      dtype='object')

## 1.3. Data Types

In [50]:
df1.dtypes

emissor                        object
no pedido                      object
revenda                        object
cidade                         object
produto                        object
quantidade                      int64
preço                         float64
total                         float64
data de emissão        datetime64[ns]
data de faturamento    datetime64[ns]
tipo de vencimento             object
data de vencimento     datetime64[ns]
% comissão                    float64
comissão total                float64
comissão 1                    float64
comissão 2                    float64
dtype: object

## 1.4. Check NA

In [51]:
# Substitui valores nulos na coluna 'data_de_faturamento' por 'data_de_emissao'
df1['data de faturamento'] = df1['data de faturamento'].fillna(df1['data de emissão'])

In [52]:
df1.isna().sum()

emissor                10
no pedido              14
revenda                 0
cidade                  0
produto                 0
quantidade              0
preço                   0
total                   0
data de emissão         0
data de faturamento     0
tipo de vencimento     23
data de vencimento      5
% comissão              0
comissão total          0
comissão 1              0
comissão 2              0
dtype: int64

## COMISSÃO

In [53]:
# Garante que as datas estejam no formato datetime
df1['data de faturamento'] = pd.to_datetime(df1['data de faturamento'], errors='coerce')
df1['data de vencimento'] = pd.to_datetime(df1['data de vencimento'], errors='coerce')

# Cria as duas tabelas
com1 = df1[['data de faturamento', 'comissão 1']].copy()
com1['mês'] = com1['data de faturamento'].dt.month.astype('Int64')
com1['ano'] = com1['data de faturamento'].dt.year.astype('Int64')
com1 = com1.groupby(['ano', 'mês'], as_index=False)['comissão 1'].sum()

com2 = df1[['data de vencimento', 'comissão 2']].copy()
com2['mês'] = com2['data de vencimento'].dt.month.astype('Int64')
com2['ano'] = com2['data de vencimento'].dt.year.astype('Int64')
com2 = com2.groupby(['ano', 'mês'], as_index=False)['comissão 2'].sum()

# Junta as duas
comissoes = pd.merge(com1, com2, on=['ano', 'mês'], how='outer').fillna(0)

# Soma total
comissoes['comissão_total_mes'] = comissoes['comissão 1'] + comissoes['comissão 2']

# Nome do mês em português
#comissoes['nome_mês'] = pd.to_datetime(comissoes['mês'], format='%m').dt.strftime('%B').str.capitalize()

# Ordena corretamente
comissoes = comissoes.sort_values(['ano', 'mês']).reset_index(drop=True)

# Reorganiza colunas
comissoes = comissoes[['ano','mês', 'comissão 1', 'comissão 2', 'comissão_total_mes']]

In [54]:
comissoes.to_csv('../data/comissao.csv')

## ULTIMOS PEDIDOS

In [55]:
# Agrupa por revenda e cidade para pegar a última data de emissão
ultimos_pedidos = (
    df1.groupby(['revenda', 'cidade'], as_index=False)['data de emissão']
    .max()
    .rename(columns={'data de emissão': 'ultima_data_emissao'})
)

# Calcula quantos dias se passaram desde o último pedido
data_atual = pd.Timestamp.today().normalize()
ultimos_pedidos['dias_sem_pedido'] = (data_atual - ultimos_pedidos['ultima_data_emissao']).dt.days

# Formata a data no padrão dd-mm-YYYY
ultimos_pedidos['ultima_data_emissao'] = ultimos_pedidos['ultima_data_emissao'].dt.strftime('%d-%m-%Y')

# Ordena da revenda mais "parada" para a mais recente
ultimos_pedidos = ultimos_pedidos.sort_values('dias_sem_pedido', ascending=False)

ultimos_pedidos

,revenda,cidade,ultima_data_emissao,dias_sem_pedido
3,Agrogarcia Insumos,Três Pontas,07-10-2022,1305
25,Casa do Café,Franca,08-11-2022,1273
29,Cooperbatata,Sacramento,05-01-2023,1215
16,Casa do Adubo,Mogi Mirim,27-02-2023,1162
38,Ouro Safra,Itapetininga,29-03-2023,1132
40,Ouro Safra,Santa Cruz do Rio Pardo,11-04-2023,1119
39,Ouro Safra,Pilar do Sul,12-04-2023,1118
44,Qualicitrus,Mogi Mirim,11-05-2023,1089
43,Qualicitrus,Casa Branca,11-05-2023,1089
45,Qualicitrus,Pouso Alegre,11-05-2023,1089
46,Qualicitrus,Sumaré,11-05-2023,1089
28,Cooperbatata,Casa Branca,17-07-2023,1022
47,R Agro,Caconde,26-07-2023,1013
30,D’Agro,Itapetininga,11-01-2024,844
1,Agro Neto,Pilar do Sul,19-03-2024,776
12,Casa do Adubo,Contagem,16-04-2024,748
37,Nova Geração,Cambui,01-08-2024,641
42,Produtiva Agropecuaria,Socorro,06-09-2024,605
35,Naroca,Maria da Fe,27-09-2024,584
2,Agrofert,Lambari,22-10-2024,559
33,Fitovet,Paraguaçu,17-02-2025,441
22,Casa do Adubo,Serra,07-08-2025,270
20,Casa do Adubo,Pouso Alegre,07-08-2025,270
18,Casa do Adubo,Nova Friburgo,07-08-2025,270
15,Casa do Adubo,Marabá,07-08-2025,270
14,Casa do Adubo,Indaiatuba,07-08-2025,270
13,Casa do Adubo,Imperatriz,07-08-2025,270
17,Casa do Adubo,Montes Claros,07-08-2025,270
9,Armazem Agricola,Vinhedo,15-09-2025,231
21,Casa do Adubo,Redenção,23-09-2025,223
23,Casa do Adubo,Uberaba,23-09-2025,223
26,Casal Comércio,Indaiatuba,20-10-2025,196
10,Bonagro,Senador Amaral,30-10-2025,186
11,Casa do Adubo,Capao Bonito,20-11-2025,165
24,Casa do Adubo,Vargem Grande do Sul,02-12-2025,153
19,Casa do Adubo,Pilar do Sul,02-12-2025,153
27,Comercial Martins Bento,Bueno Brandao,11-12-2025,144
8,Armazem Agricola,Campinas,16-12-2025,139
34,Minas Sul,Três Corações,09-01-2026,115
41,Parceria Agrícola,Camanducaia,09-01-2026,115
32,Fazenda São Marco,Itapeva,12-01-2026,112
31,Equilibrio Agricola,Mogi Mirim,12-01-2026,112
4,Agroserv,Itamogi,24-01-2026,100
6,Agrotecnica,Matão,10-02-2026,83
36,Nogueira e Oliveira,Poços de Caldas,02-03-2026,63
7,Agroterra,Munhoz,25-03-2026,40
5,Agrotata,Ipuiúna,14-04-2026,20
0,Agricola Pinhotti,Congonhal,24-04-2026,10

In [56]:
ultimos_pedidos.to_csv('../data/ultimos_pedidos.csv', index=False, encoding='utf-8-sig')

# 2.0. Engenharia de Features

In [57]:
df2 = df1.copy()

## 2.1. Ano e Mes

In [58]:
# year
df2['ano'] = df2['data de faturamento'].dt.year

# month
df2['mes'] = df2['data de faturamento'].dt.month

## 2.2. Produto Geral

In [59]:
df2['produto_geral'] = df2['produto'].apply(lambda x: x.split()[0])

## 2.3. Latitude e Longitude

In [ ]:
# Criação das colunas 'latitude' e 'longitude'
df2[['latitude', 'longitude']] = df2['cidade'].apply(
    lambda city: pd.Series(get_lat_lon(city))
)

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Pilar do Sul',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 475, in _request
    raise AdapterHTTPError(
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Pilar do Sul',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 475, in _request
    raise AdapterHTTPError(
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter swallowed an error after 2 retries. Called with (*('Pilar do Sul',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 475, in _request
    raise AdapterHTTPError(
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter caught an error, retrying (0/2 tries). Called with (*('Pilar do Sul',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 475, in _request
    raise AdapterHTTPError(
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Pilar do Sul',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 475, in _request
    raise AdapterHTTPError(
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter swallowed an error after 2 retries. Called with (*('Pilar do Sul',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 475, in _request
    raise AdapterHTTPError(
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter caught an error, retrying (0/2 tries). Called with (*('Pilar do Sul',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 475, in _request
    raise AdapterHTTPError(
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Pilar do Sul',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 475, in _request
    raise AdapterHTTPError(
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter swallowed an error after 2 retries. Called with (*('Pilar do Sul',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 475, in _request
    raise AdapterHTTPError(
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter caught an error, retrying (0/2 tries). Called with (*('Pilar do Sul',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 475, in _request
    raise AdapterHTTPError(
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Pilar do Sul',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 475, in _request
    raise AdapterHTTPError(
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter swallowed an error after 2 retries. Called with (*('Pilar do Sul',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 475, in _request
    raise AdapterHTTPError(
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter caught an error, retrying (0/2 tries). Called with (*('Lambari',), **{}).
Traceback (most recent call last):
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "c:\Users\Pedro\anaconda3\envs\indofil_env\lib\site-packages\geopy\adapters.py", line 447, in get_json

## 2.4. Total Por cidade

In [33]:
# Agrupar por cidade e somar os valores da coluna 'total'
city_total = df2.groupby('cidade')['total'].sum()

# Criar uma nova coluna no DataFrame original com os valores somados para cada cidade
df2['total_por_cidade'] = df2['cidade'].map(city_total)

In [34]:
# Dicionário com nomes dos meses em português
meses = {
    1: "Janeiro", 2: "Fevereiro", 3: "Março",
    4: "Abril", 5: "Maio", 6: "Junho",
    7: "Julho", 8: "Agosto", 9: "Setembro",
    10: "Outubro", 11: "Novembro", 12: "Dezembro"
}

df2['mes_nome'] = df2['mes'].map(meses)

In [35]:
df2['safra'] = df2.apply(define_safra, axis=1)

In [45]:
mapa_mes_safra = {
    5: 1, 6: 2, 7: 3, 8: 4, 9: 5, 10: 6,
    11: 7, 12: 8, 1: 9, 2: 10, 3: 11, 4: 12
}

df2['mes_safra'] = df2['mes'].map(mapa_mes_safra)

# 3.0 Selecionar Colunas

In [54]:
vendas = df2.loc[:, ['revenda', 'cidade', 'produto', 'quantidade', 'preço', 'total', 'ano', 'mes', 'mes_nome',  'produto_geral', 'latitude', 'longitude', 'total_por_cidade', 'safra', 'mes_safra']]

In [56]:
vendas.to_csv('../data/vendas.csv')

In [69]:
aux3 = vendas[['produto_geral', 'preço', 'mes_safra', 'safra', 'mes_nome']].groupby(['produto_geral', 'safra', 'mes_safra', 'mes_nome'], as_index=False).mean()
aux3['preço'] = aux3['preço'].round(2)
aux3

   produto_geral  safra  mes_safra   mes_nome  preço
0        Indozeb  22/23          7   Novembro  26.80
1        Indozeb  22/23          9    Janeiro  24.00
2        Indozeb  22/23         10  Fevereiro  21.75
3        Indozeb  23/24          6    Outubro  24.70
4        Indozeb  24/25          4     Agosto  24.74
..           ...    ...        ...        ...    ...
62      Moximate  25/26          2      Junho  38.19
63      Moximate  25/26          3      Julho  38.51
64      Moximate  25/26          6    Outubro  38.08
65        Xopotó  22/23          2      Junho  21.83
66        Xopotó  22/23          3      Julho  20.47

[67 rows x 5 columns]